import { CassandraTypes } from "./types/mainTypes";

export const serializationAbility = {
  [CassandraTypes.custom]: false,
  [CassandraTypes.ascii]: false,
  [CassandraTypes.bigint]: false,
  [CassandraTypes.blob]: false,
  [CassandraTypes.boolean]: false,
  [CassandraTypes.counter]: false,
  [CassandraTypes.decimal]: false,
  [CassandraTypes.double]: false,
  [CassandraTypes.float]: false,
  [CassandraTypes.int]: false,
  [CassandraTypes.text]: true,
  [CassandraTypes.timestamp]: false,
  [CassandraTypes.uuid]: false,
  [CassandraTypes.varchar]: false,
  [CassandraTypes.varint]: false,
  [CassandraTypes.timeuuid]: false,
  [CassandraTypes.inet]: false,
  [CassandraTypes.date]: false,
  [CassandraTypes.time]: false,
  [CassandraTypes.smallint]: false,
  [CassandraTypes.tinyint]: false,
  [CassandraTypes.list]: false,
  [CassandraTypes.map]: false,
  [CassandraTypes.set]: false,
  [CassandraTypes.udt]: false,
  [CassandraTypes.tuple]: false,
};
